version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/swarm.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  
  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  
  file_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 3

loggers:
  rgym_exp:
    level: DEBUG
    handlers: [console, file_info, file_error, file_debug]
    propagate: false
  
  genrl:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false
  
  hivemind:
    level: WARNING
    handlers: [console, file_info, file_error]
    propagate: false
  
  transformers:
    level: WARNING
    handlers: [console, file_info]
    propagate: false
  
  requests:
    level: WARNING
    handlers: [file_info]
    propagate: false

root:
  level: INFO
  handlers: [console, file_info, file_error]